export enum Language {
  ENGLISH = 'ENGLISH',
  FRANCH = 'FRANCH',
}

export enum AccountType {
  PERSON = 'PERSON',
  ENTERPRISE = 'ENTERPRISE',
}

export enum Status {
  REGISTERED = 'REGISTERED',
  EMAIL_VALIDATED = 'EMAIL_VALIDATED',
  PHONE_VALIDATED = 'PHONE_VALIDATED',
  COMPLETED = 'COMPLETED',
  KYC_VALIDATED = 'KYC_VALIDATED',
  KYB_VALIDATED = 'KYB_VALIDATED',
  REJECTED = 'REJECTED',
  DISABLED = 'DISABLED',
  DELETED = 'DELETED',
}
